// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/transacoes": {
            "post": {
                "description": "Insere uma nova transação financeira no banco de dados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transacoes"
                ],
                "summary": "Cadastrar nova transação",
                "parameters": [
                    {
                        "description": "Dados da Transação",
                        "name": "transacao",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Transacao"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Transacao": {
            "type": "object",
            "properties": {
                "data_transacao": {
                    "type": "string"
                },
                "descricao": {
                    "type": "string"
                },
                "efetivada": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "id_cartao_credito": {
                    "type": "integer"
                },
                "id_categoria": {
                    "type": "integer"
                },
                "id_compra_parcelada": {
                    "type": "integer"
                },
                "id_conta_bancaria": {
                    "type": "integer"
                },
                "id_conta_destino": {
                    "type": "integer"
                },
                "id_responsavel": {
                    "type": "integer"
                },
                "id_subcategoria": {
                    "type": "integer"
                },
                "valor": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Zoe Finance API",
	Description:      "API para gerenciamento de finanças.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
