CREATE TABLE TB_RESPONSAVEL_CONTA(
	ID		SERIAL PRIMARY KEY,
	NOME	VARCHAR(50) NOT NULL
);

CREATE TABLE TB_CATEGORIAS(
	ID				SERIAL PRIMARY KEY,
	NOME_CATEGORIA	VARCHAR(50) NOT NULL,
	SUBCATEGORIA	VARCHAR(50)	
);

ALTER TABLE TB_CATEGORIAS ADD COLUMN TIPO VARCHAR(50) CHECK (TIPO IN ('Receita', 'Despesa', 'Transferência'));

ALTER TABLE TB_CATEGORIAS DROP COLUMN SUBCATEGORIA;

CREATE TABLE TB_CONTAS_BANCARIAS(
	ID			SERIAL PRIMARY KEY,
	NOME		VARCHAR(50) NOT NULL,
	MONTANTE	DECIMAL(10,2) NOT NULL DEFAULT 0.00
)

CREATE TABLE TB_SUBCATEGORIAS (
    ID SERIAL PRIMARY KEY,
    ID_CATEGORIA INT REFERENCES TB_CATEGORIAS(ID) ON DELETE CASCADE,
    NOME_SUBCATEGORIA VARCHAR(50) NOT NULL
);

CREATE TABLE finance.TB_CARTAO_CREDITO(
	ID				SERIAL PRIMARY KEY,
	NOME			VARCHAR(50) NOT NULL,
	DIA_FECHAMENTO	INT CHECK (DIA_FECHAMENTO BETWEEN 1 AND 31),
	DIA_VENCIMENTO	INT CHECK (DIA_VENCIMENTO BETWEEN 1 AND 31),
	LIMITE			DECIMAL(10,2) DEFAULT 0.00
)

CREATE TABLE FINANCE.TB_TRANSACOES(
	ID					SERIAL PRIMARY KEY,
	DESCRICAO			VARCHAR(100) NOT NULL,
	VALOR				DECIMAL(10,2) NOT NULL,
	DATA_TRANSACAO		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	ID_CATEGORIA		INT NOT NULL REFERENCES FINANCE.TB_CATEGORIAS(ID),
	ID_SUBCATEGORIA		INT REFERENCES FINANCE.TB_SUBCATEGORIAS(ID),
	ID_RESPONSAVEL		INT NOT NULL REFERENCES FINANCE.TB_RESPONSAVEL_CONTA(ID),
	ID_CONTA_BANCARIA	INT REFERENCES FINANCE.TB_CONTAS_BANCARIAS(ID),
	ID_CARTAO_CREDITO	INT REFERENCES FINANCE.TB_CARTAO_CREDITO(ID),
	ID_CONTA_DESTINO	INT REFERENCES FINANCE.TB_CONTAS_BANCARIAS(ID),
	EFETIVADA			BOOL DEFAULT FALSE,

	CONSTRAINT chk_origem_destino_diferentes 
        CHECK (ID_CONTA_BANCARIA IS DISTINCT FROM ID_CONTA_DESTINO),
		
	CONSTRAINT chk_metodo_pagamento 
        CHECK (
            (ID_CONTA_BANCARIA IS NOT NULL AND ID_CARTAO_CREDITO IS NULL) OR 
            (ID_CONTA_BANCARIA IS NULL AND ID_CARTAO_CREDITO IS NOT NULL) OR
            (ID_CONTA_BANCARIA IS NOT NULL AND ID_CONTA_DESTINO IS NOT NULL) -- Caso de transferência
        )
);

CREATE INDEX IDX_TRANSACOES_DATA ON TB_TRANSACOES(DATA_TRANSACAO);
CREATE INDEX IDX_TRANSACOES_CATEGORIA ON TB_TRANSACOES(ID_CATEGORIA);
CREATE INDEX IDX_TRANSACOES_RESPONSAVEL ON TB_TRANSACOES(ID_RESPONSAVEL);



