SELECT * FROM FINANCE.TB_CONTAS_BANCARIAS;

ALTER TABLE FINANCE.TB_CONTAS_BANCARIAS ADD COLUMN ID_RESPONSAVEL INT REFERENCES FINANCE.TB_RESPONSAVEL_CONTA(ID);

INSERT INTO FINANCE.TB_CONTAS_BANCARIAS (NOME, MONTANTE, ID_RESPONSAVEL) VALUES ('Caixa', 0.00, 2);

select * from finance.tb_responsavel_conta;

ALTER TABLE FINANCE.TB_CARTAO_CREDITO ADD COLUMN ID_RESPONSAVEL INT REFERENCES FINANCE.TB_RESPONSAVEL_CONTA(ID);

select * from finance.TB_CARTAO_CREDITO;

INSERT INTO FINANCE.TB_CARTAO_CREDITO (
	NOME,
	DIA_FECHAMENTO,
	DIA_VENCIMENTO,
	LIMITE,
	ID_RESPONSAVEL
) VALUES (
	'Caixa',
	19,
	28,
	5700.00,
	2
);

select * from finance.tb_categorias;
select * from finance.tb_subcategorias;


INSERT INTO FINANCE.TB_CATEGORIAS (
	NOME_CATEGORIA,
	TIPO
) VALUES (
	'Equipamentos',
	'Despesa'
);

select * from finance.TB_TRANSACOES;

CREATE TABLE FINANCE.TB_COMPRAS_PARCELADAS(
	ID				SERIAL PRIMARY KEY,
	DESCRICAO		VARCHAR(100) NOT NULL,
	VALOR_TOTAL		DECIMAL(10,2) NOT NULL,
	QTD_PARCELAS	INT NOT NULL CHECK(QTD_PARCELAS > 0),
	DATA_COMPRA		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ID_CARTAO		INT NOT NULL REFERENCES FINANCE.TB_CARTAO_CREDITO(ID),
	ID_CATEGORIA	INT NOT NULL REFERENCES FINANCE.TB_CATEGORIAS(ID),
	ID_RESPONSAVEL	INT NOT NULL REFERENCES FINANCE.TB_RESPONSAVEL_CONTA(ID)
);

ALTER TABLE finance.TB_TRANSACOES 
ADD COLUMN ID_COMPRA_PARCELADA INT REFERENCES finance.TB_COMPRAS_PARCELADAS(ID) ON DELETE CASCADE;